#define ADC_BUF_OFFSET 32

#define ADC_BUF_STATUS_IDX 0
#define ADC_BUF_STATUS_EMPTY 10
#define ADC_BUF_STATUS_BUF0 1
#define ADC_BUF_STATUS_BUF1 2
#define ADC_BUF_LEN_SAMPLES 768

#define BITS_PER_SAMPLE 16

