#define ADC_BUF_OFFSET 32
#define SAMPLE_COUNT_IDX 4

#define ADC_BUF_STATUS_IDX 0
#define ADC_BUF_STATUS_EMPTY 10
#define ADC_BUF_STATUS_BUF0 0
#define ADC_BUF_STATUS_BUF1 1
#define ADC_BUF_LEN_SAMPLES 512

#define BITS_PER_SAMPLE 32

